MOUSEKEY_ENABLE = yes     # Mouse keys
# RGBLIGHT_ENABLE = yes    # Enable WS2812 RGB underlight.
VIA_ENABLE      = yes    # Enable VIA
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
# TAP_DANCE_ENABLE = yes
# OLED_ENABLE     = yes
# OLED_DRIVER     = SSD1306
LTO_ENABLE      = yes
